### ISSUE TITLE
Live ALPR Feed has gone with 12-01-2024 | v0.1.4 update

### ISSUE THREAD

**Issue by olympia** [algertc/ALPR-Database#16] opened 2024-12-02 09:22 UTC
Hi Charlie,

After updating to version 0.1.4 on 12-01-2024, the Live ALPR feed has gone blank:
![image](https://github.com/user-attachments/assets/edf890c0-196d-4758-9fdd-50ea018f4392)

The plate database and known plates still appear as expected. 

Do you have any idea why this might be happening? Should I take any action with the `migrations.sql` file? The instructions regarding it are unclear.

**Comment by algertc** [comment] 2024-12-02 10:16
**This is caused by the addition of the camera_name column to that table.** I added instructions to the latest release explaining what to do, but my solution for the update instructions is not the most optimal since I don't have a way to update the instructions for people on previous versions. 

The new migrations file is a remedy for my original misunderstanding of how the docker database entrypoint worked. The instructions shouldn't change from now on. 

Did you just notice that the migrations file was added / see it referenced in the compose file, or did your update alert show it? 

### Solution:
You do indeed need the migrations.sql file. Please download it and place it in the same directory as the compose and schema files. Please also update your compose file with the latest changes in the db section. With this, the issue should be resolved after restarting the docker stack - `docker compose down` `docker compose up -d`

If the issue persists, that means there's a problem with my command in the compose file. Please let me know if that's the case, and I'll fix it.

Hopefully you don't need to do this, but a quick fix if that does turn out to be the situation is to just manually add the camera_name column. You can do this with an SQL client like PgAdmin with the following command.

`ALTER TABLE IF EXISTS public.plate_reads 
    ADD COLUMN IF NOT EXISTS camera_name character varying(30);`


I apologize for the confusion!

**Comment by olympia** [comment] 2024-12-02 11:03
You might remember me as one of the unRAID users who had a long discussion in another thread with someone else about getting this setup working on unRAID. So, using the Docker Compose approach isn’t suitable for me.  

However, based on your explanation, I managed to get it running! I just needed to map the `migrations.sql` file and then manually execute `psql -U postgres -d postgres -f /migrations.sql` from the Docker console. Everything is back online now—thanks a lot for your help!  

You were thinking about the update instructions: if you have the time and energy (I really know it's painful), it would be great to highlight such breaking changes in the `CHANGELOG.md`. I always check the changelog, which is how I noticed the `migrations.sql` file, though I wasn’t sure what to do with it. (Admittedly, I could have checked the Docker Compose setup too. 😅)

**Comment by algertc** [comment] 2024-12-02 15:23
Ah, yes, no compose, my apologies. Thank you for all of your assistance with that. Please do still contribute those UnRaid instructions if you're able.

This is only a breaking change in the unraid use case since the compose file isn't used. I did add more clear guidance in a comment in the compose file when you opened this issue, also updated the empty state of the live feed page to mention this in case anyone else encounters it.

In any case, there shouldn't be any other issues with the schema moving forward now that I have fixed my original incorrect approach. 

Once there are no more bug reports and the code is a bit more flushed out, I can submit it to the Unraid container repo which would be much more streamlined. 


Any other feature ideas? I just found someone's fork that was trying to use the data for automations in homeassistant. It seems like this is in demand, so I will probably add webhook capability next. I'm wondering what else might be valuable...

**Comment by olympia** [comment] 2024-12-02 15:30
Shall I really bomb you with cosmetic UI features? I could have some in mind :)

**Comment by algertc** [comment] 2024-12-02 15:39
Absolutely. I know it doesn't scale for mobile or anything tiny. Not too concerned about that for now. 

If you have other suggestions definitely do share. Always good to hear.

**Comment by olympia** [comment] 2024-12-02 15:46
Shall I open one issue for each or just list here?

**Comment by algertc** [comment] 2024-12-02 15:52
I'll close this since it is resolved. I turned on discussions. See if you can write there...

**Closed by algertc** 2024-12-02 15:52 UTC

**Comment by olympia** [comment] 2024-12-02 16:17
Added quite a few there :)
